### ISSUE TITLE
Can you include intensity selector for dynamic background

### ISSUE THREAD

**Issue by ghost** [samuelsong70/obsidian-dynamic-background#2]
Thanks for the matrix dynamic background. 👨🏻‍💻

But the issue with that background is it is too bright🔆. So, can you implement a setting to increase or decrease the intensity/brightness of the background?

Also, can you check whether the wallpaper functionality🖼️ and blur function 😶‍🌫️are working properly or not when using the matrix background?

Thank You🙏🏻🥰

**Comment by samuelsong70** [comment]
> But the issue with that background is it is too bright🔆. So, can you implement a setting to increase or decrease the intensity/brightness of the background?

Are you saying that the falling numbers are too bright? If yes, I can add an option to adjust the color of the numbers.

>Also, can you check whether the wallpaper functionality🖼️ and blur function 😶‍🌫️are working properly or not when using the matrix background?

I also noticed this problem before the release, but I haven't found a solution yet, because when drawing the trail of falling numbers, I need to use a background color to control it, so the wallpaper cannot be displayed. I'll keep looking for a solution, please take it easy.

**Comment by ghost** [comment]
Thanks for the faster response and good luck with your work

Your plugin have given my notes a new life, really liked it

**Comment by samuelsong70** [comment]
The wallpaper functionality🖼️ and blur function 😶‍🌫️are working properly now when using the matrix background. 

While solving the above problems, the digital rain is not so dazzling, so the function of adjusting the brightness is not added this time.

Thank you for liking this plugin and good luck with your work.

**Comment by ghost** [comment]
Thanks

if adjusting brightness is not workable, can you put a low intensity version of that dynamic effect.

**Comment by samuelsong70** [comment]
Hi, the brightness control function has beed added to Matrix digital rain dynamic effect. Please upgrade to the lastest version (v1.0.5).

**Comment by ghost** [comment]
Thanks a lot 😘
