### ISSUE TITLE
It doesn't work in the latest version of obsidian

### ISSUE THREAD

**Issue by 76563** [samuelsong70/obsidian-dynamic-background#4]
Hi! I REALLY like this plugin because it can help me change the background of my notes and have so many beautiful dynamic background effects.
But when I upgraded obsidian from v.0.14.6 to v.1.1.9, it doesn't work anymore, neither static wallpaper images nor dynamic backgrounds work anymore.Even if I reinstalled obsidian, the situation still hasn't changed.I noticed that the plugin was last updated on 11.30, hope you can fix this problem！

![image](https://user-images.githubusercontent.com/106232184/211480451-b6df7d81-2ec0-4d76-92a8-7512d4fa7684.png)

Another small suggestion: can you design two options for the static wallpaper background? One for light and one for dark.  It will be more convenient when switching between light/dark. Thank you!

**Comment by samuelsong70** [comment]
I am using Obsidian 1.1.9, the Obsidian Dynamic Background pulgin (v1.0.5) works well. You can try to delete the plugin folder (vault/.obsidian/plugins/obsidian-dynamic-background/) and reinstall the plugin again.  You can contact me using WeChat. My WeChat number is: ReadingHere2000.  Thanks for your suggestion. I'm busy right now, I'll try to fix this in a while.
