### ISSUE TITLE
[Feature request] Adding custom effects

### ISSUE THREAD

**Issue by trochumski** [samuelsong70/obsidian-dynamic-background#5]
Not sure it this is a feature request or a bug
but when I add path to static wallpaper that is a `*.gif` the plugin doesn't display it.

It would be nice to have an editor to create those effects.

Also, good job with the plugin :)

**Comment by samuelsong70** [comment]
Hi，

Static wallpaper image files do not support wildcards, such as *.gif, you can use absolute paths or relative paths to point to specific image file names, such as e:\\images\\demo.gif (windows) or /home/user/images/demo.gif (Linux) or attachments/demo.gif.

At present, dynamic effects are controlled by JavaScript, and codes need to be written. There is currently no proper way to build an editor. But I will consider your suggestion.

I'm glad you like this plugin, thanks.
