### ISSUE TITLE
static wallpaper image not work

### ISSUE THREAD

**Issue by VinciYan** [samuelsong70/obsidian-dynamic-background#8]
obsidian v1.3.0+

app://local/

should be like

this.app.vault.adapter.getResourcePath(this.settings.backgroundImageFile)

**Comment by Faris999** [comment]
My background doesn't appear after updating as well. However, your workaround doesn't work either. The `getResourcePath` function returns a new URL that looks like `app://{vault hash}/{vault location}/{file location}`. But when I changed the URL to the given one, it still doesn't work. It still throws a `net::ERR_FILE_NOT_FOUND` error. Did you make it to work? Let me know of any other workarounds ^^

**Comment by Faris999** [comment]
Ah, apparently the file location needs to be relative to the vault. Now it worked again, thanks!!

**Comment by samuelsong70** [comment]
Thanks for your feedback, I have updated the code. The lastest version is 1.0.6.
