### ISSUE TITLE
Not working in annuppuchin theme

### ISSUE THREAD

**Issue by Gourav1910** [samuelsong70/obsidian-dynamic-background#9]
Hi your plugin is working in default theme but not in annuppchin theme. What to do to make it work?

This is what showing in annuppuchin theme.
![image](https://github.com/samuelsong70/obsidian-dynamic-background/assets/101202140/fc73c147-4191-4015-b1e0-4291944cb4b8)

And in default theme it is working.
![image](https://github.com/samuelsong70/obsidian-dynamic-background/assets/101202140/5c6d4e3e-0af3-42e1-b5f6-4e1cd22fea4d)

**Comment by samuelsong70** [comment]
Hi, there are some conflicts between some themes and this plug-in, and there is currently no good solution. You can consider choosing a theme that does not conflict with this plug-in. Thank you for your attention.
